### ISSUE TITLE
jdk download fails when running common/tasks/java.yml

### ISSUE THREAD

**Issue by kevin-bates** [lresende/ansible-spark-cluster#16]
The following failure is occurring when attempt to run the setup-ambari-cluster playbook:

```fatal: [elyra-wtf2]: FAILED! => {"changed": false, "dest": "/tmp/ansible-install/jdk-8u144-linux-x64.rpm", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.rpm"}```

After thinking this might be because 8u144 is no longer available, I attempted to update the files to use 8u152 after determining the appropriate build identifier and md5 hash, but got the same kind of issue: 

```fatal: [elyra-wtf2]: FAILED! => {"changed": false, "dest": "/tmp/ansible-install/jdk-8u152-linux-x64.rpm", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/8u152-b16/b6979be30bdc4077dc93cd99134ad84d/jdk-8u152-linux-x64.rpm"}```

Since there doesn't seem to be a way to "get the latest", it would be nice to figure out a better way to determine the download url and what is causing the `404` exception.

The workaround is to download the appropriate `rpm` file to `/tmp/ansible-install` on each node, then update `roles/common/defaults/main.yml` with any file name changes, `roles/common/tasks/main.yml` to not delete the `install_temp_dir` directory, and `roles/common/tasks/java.yml` to not delete the `rpm` from the `install_temp_dir` and not perform the download.

**Comment by akchinSTC** [comment]
Looks like the download link is not valid because it oracle requires a header/cookie that says you accepted the license to download the jdk. The easiest workaround would be to change the url to a mirror or alternative trusted site.
