### ISSUE TITLE
Enable to load kernels using entreprise_gateway?

### ISSUE THREAD

**Issue by ziedbouf** [lresende/ansible-spark-cluster#25]
Thanks for this solution, we love the idea of connecting jupyter notebooks to spark cluster. I gone through the following [ansible playbook](https://github.com/lresende/ansible-spark-cluster/issues/14) and i was able to get the setup up and running on gcloud compute engine. Right now i am facing an issue while trying to connecting my jupyter notebook to the cluster `[W 21:49:37.661 NotebookApp] Error loading kernelspec 'python3'` and i am not able to catch what i am missing. I follow up the following instruction to connect my notebook:

`export KG_URL=http://spark-master:8888
export KG_HTTP_USER=elyra
export KG_HTTP_PASS=
export KG_REQUEST_TIMEOUT=30
export KERNEL_USERNAME=${KG_HTTP_USER}
jupyter notebook \
  --NotebookApp.session_manager_class=nb2kg.managers.SessionManager \
  --NotebookApp.kernel_manager_class=nb2kg.managers.RemoteKernelManager \
  --NotebookApp.kernel_spec_manager_class=nb2kg.managers.RemoteKernelSpecManager` 

Any help on this?

**Comment by lresende** [comment]
@ziedbouf Could you please attach more info from the logs: client (notebook) and server(gateway)
Also, are you using this with Spark Standalone? Have you installed NB2KG on the machine where you are running the notebook? 

Some other references might also help:
 - [enabling support for spark standalone](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-client-mode.html)
 - [Connecting Jupyter Notebook to Enterprise Gateway](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started.html#connecting-a-notebook-to-enterprise-gateway)

**Comment by ziedbouf** [comment]
I was a mistake from mys side when installing NB2KG to activate the extension on client side, we need to enable NB2KG as an extension:
`
jupyter serverextension enable --py nb2kg --sys-prefix
`

Thanks @lresende  for the support.
